sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        erXHyylWvumuLGH8DqTgDbVeV7gdUGQiWDyYPkP8QA9KLva4OBRC9UXU1g3yuoZ/INYEFKmqlpInYGPpTLF+EW7kuu8Tt8sdKQtU5akou/etPlSLYjVg+43kvp6YJBHIq0aHg6+u6yZSOSfPLHzkqkgA2h9AFoVAi/OazTCzb5XoEogHXafC0dhRD4Tyj6C/V8VOf0NakSwJnxF1yvvhe/chemwD61VPYbDeuJg7qpRdmg7tvBpkaG1jGqn7CHs9tAiYjzFnFV6C45NzPcPt2Gu+2WejDwBHY3XWbwjhhyTAw7lVuuPQxd3MpLQpR2vgkzeTGXCGyQbuRAN8KuVmtThVbKccvFAO3P/Dpz5bQ8UEmDnBLtk13utG5jGFY8MF4/1qsQwgMfDETg/bnQ7c8/5gRgPNBvZnSbg54adpLKhtCHRjCvT92L3yryyB4P39BTLoNrgxM1EH/zpN6UuEe3yZTqfeKEGWdOYNlGgZ7CDMF+/FYHwK90a5gIVDE6dMvZQWDFDHLaHJKwzLqappjz10ueShWPFov3i5YzWQyCW4pf5OnFC7VpjOak41bDNVOGD3qoz6qPPc7qtkm9FyPwvARjrKKpV29/GeMuYc6r7IAAwXWnshPK8IlqRanZu4/+XNIWt0A4mjChpCXIlj8oa4LR9/u7jtI6Sj9Mlh9Rk=
    - secure: >-
        rh/zE+gUk1qOdkGiSbcA/d/Ay3TNF1cuKCHo61l7ZU0e81dErQd9sE2lrq9RQ7toBwNGCnRCRwsdhIVvSqfMeZF+dJi1NqqgXs2CK/y6uBPeZpXo1D8McJpXoJxVf1rezrtGaZJjP0tGCL97d9oianrAcR6FXwwU5/Kcp4rrrve4colLWdWyyws1DXiHBNdrL1iZwkJocSjQz4xoR6qlsxuKEeYklEO/OYTntJr3xQKA0ZyyCtYN2B1cUO0pTn2aMcp8lLjVYNX4cIvf41/QL/8qqS/0MTjXSjwEc6pvDVtxJwewOllC9lLgl8jsHM5xTl3gcDt72z2/jXnERR7h7wFBeajxvPOpF/QNBEoMEMJDm49dqXha8voMtnBsU1Cfbx5BQ2HSONpq1GoJtQkuwKms1iJXUz7oBsZJh4KjQER/uTVIHFbzyfobjMkU6otkBxcphqyLVE4G8+yo/buip1+G+pdAQh3Qxk+vQSyAR9EyKa3aEoDxUtUcWWgTkFinKBqVdpR+braLVHBW5l1InWUaaRdTCNrSEfFzqhbnkUtueiN+k1kK0kFU0jzCI4YPUX/f0HUBimyFz2UBE+95vSQi2Bkysc8HcnTQZvxqy2WAgNtJ9UqKagKDCBa0/lFLfvLs50vK0JFlbHjR6Gp0B+mkyHYXuO1T7qH5iNLavNE=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
